# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40262a8ccf7f650c20f261dc58277cc3d1fb478c2e33c2707036595b8d4a6b732cd826a9ebbb9613cee97627c5097d6c11f2407ff2ef57e1e162c74bf3e627cf

test:
  secret_key_base: 95487515854e96401b2d74c6d0d0d831b220ebf188d2be0d7d2751434bea75ca58144f9bff923390c32651f30a39c45ebef8dcf0eb469eda6cb46f3f3bddea97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
